server:
  port: 8081
spring:
  application:
    name: mod-requests-mediated
  datasource:
    username: ${DB_USERNAME:folio_admin}
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  sql:
    init:
      # to boot up application despite of any DB connection issues
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  mustache:
    check-template-location: false
  cloud:
    openfeign:
      okhttp:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
    consumer:
      auto-offset-reset: latest
      group-id: ${ENV:folio}-mod-requests-mediated-group
folio:
  tenant:
    secure-tenant-id: ${SECURE_TENANT_ID}
    validation:
      enabled: true
  environment: ${ENV:folio}
  okapi-url: ${OKAPI_URL:http://okapi:9130}
  system-user:
    enabled: ${SYSTEM_USER_ENABLED:true}
    username: ${SYSTEM_USER_NAME:mod-requests-mediated}
    password: ${SYSTEM_USER_PASSWORD:mod-requests-mediated}
    lastname: System
    permissionsFilePath: permissions/mod-requests-mediated.csv
  batch-requests:
    thread-pool-size: ${BATCH_REQUEST_THREADS_NUM:4}
    execution-timeout: ${BATCH_REQUEST_EXECUTION_TIMEOUT:10m}
    last-executions-status-cache-size: ${BATCH_REQUEST_LAST_EXECUTIONS_CACHE_SIZE:25}
    print-result: ${BATCH_REQUEST_PRINT_RESULTS:false}
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace
      base-path: /admin
  #  endpoint:
  #    health:
  #      show-details: always
  #      show-components: always
  ###################################################
  # Disable all checks except for readiness
  ###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
debug: false
